version: '3.4'
services:
  webserver:
    image: nginx:1.15.8
    networks:
      - esnet
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.website.com
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/conf:/usr/share/logstash/pipeline
    networks:
      - esnet
      
volumes:
  esdata1:
    driver: local

networks:
  esnet:
